config/routes.rb
Rails.application.routes.draw do
  resources :creditdetails
  get 'home/index'
  root 'home#index'
  post '/approval' => 'home#approval'
  post '/payment' => 'home#payment'
  get '/users' => 'users#sign_up'
  devise_for :users

end

app/models/creditdetail.rb
class Creditdetail < ActiveRecord::Base
	belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :Creditdetails, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  /protect_from_forgery with: :exception/
   before_filter :configure_permitted_parameters, if: :devise_controller?
   protected

   def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys:[:firstName, :lastName, :email, :password])
            devise_parameter_sanitizer.permit(:account_update,keys:[:firstName,:lastName, :email, :password])
   end
end

app/controllers/creditdetails_controller.rb
class CreditdetailsController < ApplicationController
  before_action :set_creditdetail, only: [:show, :edit, :update, :destroy]

  # GET /creditdetails
  # GET /creditdetails.json
  def index
    @creditdetails = Creditdetail.all
  end

  # GET /creditdetails/1
  # GET /creditdetails/1.json
  def show
  end

  # GET /creditdetails/new
  def new
    @creditdetail = Creditdetail.new
    @creditdetail.user_id=current_user.id
  end

  # GET /creditdetails/1/edit
  def edit
  end

  # POST /creditdetails
  # POST /creditdetails.json
  def create
    @creditdetail = Creditdetail.new(creditdetail_params)

    respond_to do |format|
      @creditdetail.user_id=current_user.id
      if @creditdetail.amount!=nil&&current_user.cl>=@creditdetail.amount&&@creditdetail.amount>0&&@creditdetail.save
        current_user.cl = current_user.cl - @creditdetail.amount
        current_user.save
        format.html { redirect_to '/', notice: 'Credit request was successfully created.' }
        format.json { render :show, status: :created, location: @creditdetail }
      else
        if @creditdetail.amount==nil
        format.html { redirect_to '/', alert: 'Plz specify the amount' }
      elsif @creditdetail.amount <= 0
        format.html { redirect_to '/', alert: 'Plz enter amount greater than zero' }
      else
        format.html { redirect_to '/', alert: 'Out of Your credit limit' }
      end
          
        format.json { render json: @creditdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creditdetails/1
  # PATCH/PUT /creditdetails/1.json
  def update
    respond_to do |format|
      if @creditdetail.update(creditdetail_params)
        format.html { redirect_to @creditdetail, notice: 'Creditdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @creditdetail }
      else
        format.html { render :edit }
        format.json { render json: @creditdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creditdetails/1
  # DELETE /creditdetails/1.json
  def destroy
    @creditdetail.destroy
    respond_to do |format|
      format.html { redirect_to creditdetails_url, notice: 'Creditdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creditdetail
      @creditdetail = Creditdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creditdetail_params
      params.require(:creditdetail).permit(:amount, :repaidAmount, :isPaid, :requestStatus,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
  end
  def approval

  	id = params[:id]
	cd = Creditdetail.find_by_id(id);
  	cd.requestStatus = 1
  	cd.save
  	
  	return redirect_to '/',success: 'credit request accepted'
  end
  	def payment
  	id = params[:id]
  	cd = Creditdetail.find_by_id(id)
  	user = User.find_by_id(cd.user_id)
  	user.cl = user.cl + cd.amount
  	cd.repaidAmount = cd.amount
  	cd.isPaid = 1
  	user.save
  	cd.save
  	return redirect_to '/',success: 'payment successfully done'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditdetails_helper.rb
module CreditdetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/creditdetails/_form.html.erb
<%= form_for(@creditdetail) do |f| %>
  <% if @creditdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creditdetail.errors.count, "error") %> prohibited this creditdetail from being saved:</h2>

      <ul>
      <% @creditdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :repaidAmount %><br>
    <%= f.number_field :repaidAmount %>
  </div>
  <div class="field">
    <%= f.label :isPaid %><br>
    <%= f.check_box :isPaid %>
  </div>
  <div class="field">
    <%= f.label :requestStatus %><br>
    <%= f.check_box :requestStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/creditdetails/edit.html.erb
<h1>Editing Creditdetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @creditdetail %> |
<%= link_to 'Back', creditdetails_path %>

app/views/creditdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Creditdetails</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Repaidamount</th>
      <th>Ispaid</th>
      <th>Requeststatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creditdetails.each do |creditdetail| %>
      <tr>
        <td><%= creditdetail.amount %></td>
        <td><%= creditdetail.repaidAmount %></td>
        <td><%= creditdetail.isPaid %></td>
        <td><%= creditdetail.requestStatus %></td>
        <td><%= link_to 'Show', creditdetail %></td>
        <td><%= link_to 'Edit', edit_creditdetail_path(creditdetail) %></td>
        <td><%= link_to 'Destroy', creditdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creditdetail', new_creditdetail_path %>

app/views/creditdetails/new.html.erb
<h1>New Creditdetail</h1>

<%= render 'form' %>

<%= link_to 'Back', creditdetails_path %>

app/views/creditdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @creditdetail.amount %>
</p>

<p>
  <strong>Repaidamount:</strong>
  <%= @creditdetail.repaidAmount %>
</p>

<p>
  <strong>Ispaid:</strong>
  <%= @creditdetail.isPaid %>
</p>

<p>
  <strong>Requeststatus:</strong>
  <%= @creditdetail.requestStatus %>
</p>

<%= link_to 'Edit', edit_creditdetail_path(@creditdetail) %> |
<%= link_to 'Back', creditdetails_path %>

app/views/home/index.html.erb
<main>
<% if current_user.role == 1%>
<h3>You are the boss</h3>

	<table>
		<tr>
		<th colspan = "6" >
			Burrowers requests
		</th>
		</tr>
		<tr>
		<th >
			E-mail
		</th>
		<th>
			Request Amt.
		</th>
		<th>
			Request Status
		</th>
		<th>
			Balance
		</th>
		<th>
			Paid Amt.
		</th>
		<th>
			Approve
		</th>
		</tr>
		
		<%cd = Creditdetail.all%>
		<% cd.each do |f|%>
			<tr>
				<% user = User.find_by_id(f.user_id)%>
				<td >
					<%=user.email%>
				</td>
				<td>
					<%=f.amount%>
				</td>
				<td>
					<% if f.requestStatus%>
						<font color="green">Approved</font>
						<%else%>
						<font color="#ff8000">pending</font>
						<%end%>
				</td>
				<td>
					<%=user.cl%>
				</td>
				<td>
					<%=f.repaidAmount%>
				</td>
				<td>
					<%if !f.requestStatus%>
						<form action="approval" method = post>
						<input type="hidden" name="id" value="<%=f.id%>">
						<input type="submit" value="Approval">

						</form>
						<%else%>
						<font color="green">Approved</font>
					<%end%>

				</td>
			</tr>


		<%end%>

	</table>



<%else%>
<h3>BALANCE AMOUNT: <%=current_user.cl%></h3>
<%@creditdetail = Creditdetail.new%>

<%= form_for @creditdetail do |f| %>

	  <div class="field">
	    <%= f.label :amount %><br>
	    <%= f.number_field :amount %>
	  </div>
	 
	  <div class="actions">
	    <%= f.submit :Create_Credentials%>
	  </div>

<% end %>
	<% if @creditdetail.errors.any? %>
        		<% @creditdetail.errors.full_messages.each do |message| %>
   				<script type="text/javascript">
				noty({text: '<%= message %>', type: 'error'},timeout:2000);
				</script>
     		<% end %>
 	<% end %>
	<table>
		<tr>
		<th colspan = "6" >
			Your requests
		</th>
		</tr>
		<tr>
		<th>
			Request Amt.
		</th>
		<th>
			Request Status
		</th>
		<th>
			Paid Amt.
		</th>
		<th>
			Is Paid
		</th>
		<th>
			Payment Option
		</th>
		</tr>
		
		<%cd = Creditdetail.where(user_id: current_user)%>
		<% cd.each do |f|%>
			<tr>
				<% user = User.find_by_id(f.user_id)%>
				<td>
					<%=f.amount%>
				</td>
				<td>
					<% if f.requestStatus%>
						<font color="green">approved</font>
						<%else%>
						<font color="#ff8000">pending</font>
						<%end%>
				</td>
				<td>
					<%=f.repaidAmount%>
				</td>
				<td>
					<%if f.isPaid%>
						<font color="green">Yes</font>
					<%else%>
						<font color="red">No</font>
					<%end%>
				</td>
				<td>
				<%if !f.isPaid && !f.requestStatus%>
					<font color="red">Not Approved</font>

				<%elsif !f.isPaid && f.requestStatus%>
						<form action="payment" method = post>
						<input type="hidden" name="id" value="<%=f.id%>">
						<input type="submit" value="Payment">
						</form>

				<%elsif f.isPaid && f.requestStatus%>
					<font color="green">Transaction Completed</font>


				<%end%>
					
					
				</td>
			</tr>


		<%end%>

	</table>


<%end%>
</main>
<style type="text/css">
  body{
    background-color: #cc0001;
    color: white;
    
  }
 
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreditApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>

<script type="text/javascript">
	noty({text: '<%= notice %>', type: 'success', timeout: 1000});
</script>
<% end%>

<% if  alert %>
<script type="text/javascript">
	noty({text: '<%=alert %>', type: 'error',timeout: 1000});
</script>

<% end%>

<%if current_user%>
<header>
	<div class="logo">
		<%= image_tag 'images.jpg' %>
	</div>
	<div>
		<nav>
			<ul>
				<li><%=current_user.email%></li>
				<li>  <%= link_to "Sign Out",destroy_user_session_path,method: :delete ,data: {confirm:"Are you sure?"}%></li>
			</ul>
		</nav>
	</div>

</header>
<%end%>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>